# Generated by Django 4.1.6 on 2023-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('test', 'Test'), ('news', 'News'), ('sport', 'Sport')], default='test', max_length=10),
        ),
    ]
