# Generated by Django 4.1.6 on 2023-04-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Test', 'Test'), ('News', 'News'), ('Sport', 'Sport')], default='Test', max_length=10),
        ),
    ]
