# Generated by Django 4.1.6 on 2023-04-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_created_article_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('publish_article', 'Can publish article'),)},
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
